apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
        - image: jmalloc/echo-server
          name: echo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
